coderscotchCRM/urls.py
# CoderscotchCRM/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('superadmin/', include('superadmin.urls', namespace='superadmin')),  # Avoid path conflict
    path('employee/', include('employee.urls', namespace='employee')),
    path('accounts/', include('django.contrib.auth.urls')),  # Use 'accounts/' instead of root ''
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

employee/urls.py
# employee/urls.py
from django.urls import path
from .views.authentication.loginviews import employee_login, home_view, employee_logout, employee_password_reset
from .views.taskviews import employee_tasks,task_detail
from .views.leaveviews import apply_leave,leaves
from .views.projectviews import project_list,projects
    
app_name = 'employee'
urlpatterns = [

    #login urls
    path('login/', employee_login, name='employee_login'),
    path('home/', home_view, name='home_view'),
    path('reset-password/', employee_password_reset, name='employee_password_reset'),
    path('logout/', employee_logout, name='employee_logout'),
    

    #projects urls
    path('project/', project_list, name='project_list'),
    path('projects/<int:project_id>/',projects, name='projects'),

    #tasks urls
    path('tasks/', employee_tasks, name='employee_tasks'),
    path('tasks/<int:task_id>/', task_detail, name='task_detail'),  # Add this URL pattern for task details
    
    # leaves url
    path('apply-leave/', apply_leave, name='apply_leave'),
    path('leavs/', leaves, name='leaves'),
    

   

]

superadmin/urls.py
# superadmin/urls.py
from django.urls import path

from .views import clientViews, employeeview, expenseviews, invoiceviews, leadsviews, leavesview, projectviews, taskviews
from .views import views
from django.conf import settings
from django.conf.urls.static import static



app_name = 'superadmin'

urlpatterns = [
    path('home/', views.home_view, name='home'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
   
    
    path('create-superadmin/', views.edit_superadmin, name='edit_superadmin'),
    path('profile/', views.admin_profile, name='admin_profile'),
    # Client URLs
    path('clients/', clientViews.client_list, name='client_list'),
    path('clients/create/', clientViews.client_create, name='client_create'),
    path('clients/update/<int:pk>/', clientViews.client_update, name='client_update'),
    path('clients/delete/<int:client_id>/', clientViews.client_delete, name='client_delete'),
    path('clients/bulk-delete/', clientViews.bulk_client_delete, name='bulk_client_delete'),
    path('clients/upload_images/', clientViews.upload_client_images, name='upload_client_images'),
    path('clients/details/<int:client_id>/', clientViews.client_detail, name='client_detail'),

    # Employee URLs
    path('employees/', employeeview.employee_list, name='employee_list'),
    path('employees/create/', employeeview.employee_create, name='employee_create'),
    path('employees/update/<int:pk>/', employeeview.employee_update, name='employee_update'),
    path('employees/delete/<int:pk>/', employeeview.employee_delete, name='employee_delete'),
    path('employees/upload-images/', employeeview.upload_employee_images, name='upload_employee_images'),
    path('employees/delete/<int:pk>/', employeeview.employee_delete, name='employee_delete'),
    path('employees/bulk-delete/', employeeview.bulk_employee_delete, name='bulk_employee_delete'),
    path('employees/details/<int:employee_id>/', employeeview.employee_detail, name='employee_detail'),
    path('salary-slip/<int:salary_slip_id>/pdf/', employeeview.generate_salary_slip_pdf, name='salary_slip_pdf'),
    path('salary_slip/<int:salary_slip_id>/delete/', employeeview.delete_salary_slip, name='delete_salary_slip'),
   

    
    path('employee/<int:employee_id>/create-slip/', employeeview.check_or_create_salary_slip, name='check_or_create_salary_slip'),
    path('employee/<int:employee_id>/create-salary-slip/', employeeview.create_salary_slip, name='create_salary_slip'),
    path('salary_slip/<int:salary_slip_id>/', employeeview.salary_slip_detail, name='salary_slip_detail'),
    path('salary_slip/<int:salary_slip_id>/update-slip/', employeeview.update_salary_slip, name='update_salary_slip'),
    path('project/<int:project_id>/tasks/', employeeview.project_tasks, name='project_tasks'),


    # Project URLs
    path('projects/', projectviews.project_list, name='project_list'),
    path('projects/create/', projectviews.project_create, name='project_create'),
    path('projects/<int:project_id>/edit/', projectviews.project_update, name='project_update'),
    path('projects/delete/<int:project_id>/', projectviews.project_delete, name='project_delete'),
    path('projects/bulk-delete/', projectviews.bulk_project_delete, name='bulk_project_delete'),
    path('projects/<int:project_id>/', projectviews.project_detail, name='project_detail'),
    path('projects/<int:project_id>/change-request/', projectviews.change_request_create, name='change_request_create'),
    path('projects/upload_files/', projectviews.upload_project_filess, name='upload_project_filess'),

    #Task URLS
    # path('tasks/', taskviews.task_list, name='task_list'),
   
    path('kanban/', taskviews.kanban_board, name='kanban_board'),
    path('task/create/', taskviews.create_task, name='create_task'),
    path('task/update/<int:task_id>/', taskviews.update_task, name='update_task'),
    path('tasks/<int:task_id>/delete/', taskviews.task_delete, name='task_delete'),
    path('tasks/<int:task_id>/detail/', taskviews.task_detail, name='task_detail'),
    path('tasks/add_board/', taskviews.add_board, name='add_board'),
    path('kanban/edit_board/<int:board_id>/', taskviews.edit_board, name='edit_board'),
    path('kanban/delete_board/<int:board_id>/', taskviews.delete_board, name='delete_board'),
    path('update_task_board/<int:task_id>/', taskviews.update_task_board, name='update_task_board'),
    # path('upload-task-files/', taskviews.upload_task_files, name='upload_task_filess'),
    path('fetch-employees/', taskviews.fetch_employees, name='fetch_employees'),
   
    #Leads urls
    path('leads/', leadsviews.lead_list, name='lead_list'),
    path('leads/<int:pk>/', leadsviews.lead_detail, name='lead_detail'),
    path('leads/create/', leadsviews.lead_create, name='lead_create'),
    path('leads/update/<int:pk>/', leadsviews.lead_update, name='lead_update'),
    path('leads/delete/<int:lead_id>/', leadsviews.lead_delete, name='lead_delete'),
    path('leads/bulk-delete/', leadsviews.bulk_lead_delete, name='bulk_lead_delete'),
    path('leads/upload_files/', leadsviews.upload_lead_filess, name='upload_lead_filess'),
    
    # leaves urls
    path('leave-management/', leavesview.leave_management, name='leave_list'),  # For listing all leaves
    path('leave-management/<int:leave_id>/', leavesview.leave_management, name='leave_approval'), 
    
    # invoice urls
    path('invoices/', invoiceviews.invoice_list, name='invoice_list'),
    path('invoice/<int:invoice_id>/', invoiceviews.invoice_detail, name='invoice_detail'),
    path('invoices/create/', invoiceviews.invoice_create, name='invoice_create'),
    path('invoices/add_item/', invoiceviews.add_invoice_item, name='add_invoice_item'),
    path('invoice/<int:invoice_id>/edit/', invoiceviews.invoice_edit, name='invoice_edit'),
    path('invoice/<int:invoice_id>/delete/', invoiceviews.invoice_delete, name='invoice_delete'),
    path('invoice/<int:invoice_id>/item/create/', invoiceviews.invoice_item_create, name='invoice_item_create'),
    path('invoice/<int:invoice_id>/item/<int:item_id>/delete/', invoiceviews.invoice_item_delete, name='invoice_item_delete'),
    path('invoice/<int:invoice_id>/send/', invoiceviews.send_invoice_pdf, name='send_invoice_pdf'),
    path('invoice/<int:invoice_id>/download/', invoiceviews.download_invoice_pdf, name='download_invoice_pdf'),
    
    path('expenses/', expenseviews.expense_list, name='expense_list'),
   path('expense/add/', expenseviews.add_or_update_expense, name='add_expense'),
    path('expense/update/<int:pk>/', expenseviews.add_or_update_expense, name='update_expense'),
    path('expense/delete/<int:pk>/', expenseviews.delete_expense, name='delete_expense'),
    
    
]

# Serve static files during development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

employee/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from datetime import datetime
from django.apps import apps




class Leave(models.Model):
   
    employee = models.ForeignKey('superadmin.Employee', on_delete=models.CASCADE)
    leave_date = models.DateField()
    start_date = models.DateField(default=datetime.now)
    end_date = models.DateField(default=datetime.now)
    leave_reason = models.CharField(max_length=255)
    status_choices = [
        ('pending', 'Pending'),
        ('approved', 'Approved'),
        ('rejected', 'Rejected')
    ]
    status = models.CharField(max_length=10, choices=status_choices, default='pending')

    def __str__(self):
        return f"Leave ID: {self.id} - {self.employee.username} from {self.start_date} to {self.end_date}"

employee/views/projectviews.py
from django.shortcuts import render, redirect,get_object_or_404
from django.contrib.auth.decorators import login_required

from django.contrib.auth import login
from superadmin.models import Project,Client


from django.contrib.auth.decorators import login_required

from django.db.models import Q


@login_required
def project_list(request):
    employee = request.user
    search_query = request.GET.get('search_query', '')
    client_filter = request.GET.get('client', '')
    priority_filter = request.GET.get('priority', '')
    status_filter = request.GET.get('status', '')

    if search_query:
        projects = Project.objects.filter(tasks__isnull=False).distinct()(
            Q(project_title__icontains=search_query) |
            Q(client__name__icontains=search_query)
        )
    else:
        projects = employee.projects.all().order_by('-id')
        
    if client_filter:
        projects = projects.filter(client__id=client_filter)

    if priority_filter:
        projects = projects.filter(priority=priority_filter)

    if status_filter:
        projects = projects.filter(status=status_filter)
    
    clients = Client.objects.all()
    priorities = Project.PRIORITY_LEVELS
    statuses = Project.STATUS_LEVELS
    
    context = {
       'projects': projects,
        'search_query': search_query,
        'client_filter': client_filter,
        'priority_filter': priority_filter,
        'status_filter': status_filter,
        'clients': clients,
        'priorities': priorities,
        'statuses': statuses,
    }
    return render(request, 'employee/projects/projects.html', context)

def projects(request, project_id):
    """Display detailed information about a specific project."""
    project = get_object_or_404(Project, pk=project_id)
    project_files = project.files.all()  # Fetch related project files using 'files' related name
    change_requests = project.changerequest_set.all()  # Fetch related change requests
    project_tasks = project.tasks.all()  # Fetch related tasks

    return render(request, 'employee/projects/projects_details.html', {
        'project': project,
        'change_requests': change_requests,
        'project_files': project_files,
        'project_tasks': project_tasks,
    })

superadmin/views/clientViews.py
from django.shortcuts import render, redirect,get_object_or_404
from superadmin.models import Client,ClientImage
from django.contrib import messages
from ..forms import ClientForm,ClientImageFormSet
from django.urls import reverse
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.forms import modelformset_factory
from django.contrib.auth.decorators import login_required
from django.db.models import Q

@login_required(login_url='/superadmin/login/')
def client_list(request):
    clients = Client.objects.all().order_by('-id')
    search_query = request.GET.get('search', '').strip().lower()
    location = request.GET.get('location')
    industry = request.GET.get('industry')

    if search_query:
        clients = clients.filter(
            Q(name__icontains=search_query) |
            Q(email__icontains=search_query) |
            Q(phone__icontains=search_query)
        )
    if location:
        clients = clients.filter(location__icontains=location)
    if industry:
        clients = clients.filter(industry__icontains=industry)

    locations = Client.objects.values_list('location', flat=True).distinct()
    industries = Client.objects.values_list('industry', flat=True).distinct()

    context = {
        'clients': clients,
        'filters': request.GET,
        'locations': locations,
        'industries': industries,
    }
    return render(request, 'superadmin/clients/list.html', context)

@login_required(login_url='/superadmin/login/')
def client_create(request):
    if request.method == 'POST':
        form = ClientForm(request.POST)
        if form.is_valid():
            client = form.save()
            messages.success(request, 'Client created successfully.')
            return JsonResponse({'client_id': client.id}, status=200)
        else:
            return JsonResponse({'errors': form.errors}, status=400)
    else:
        form = ClientForm()
    
    return render(request, 'superadmin/clients/form.html', {'form': form})

@login_required(login_url='/superadmin/login/')
def upload_client_images(request):
    if request.method == 'POST':
        client_id = request.POST.get('client_id')
        client = get_object_or_404(Client, id=client_id)

        # Check if there are files in the request
        if 'file' in request.FILES:
            # Process each file
            for file in request.FILES.getlist('file'):
                ClientImage.objects.create(client=client, image=file)
            return JsonResponse({'status': 'success'}, status=200)
        else:
            return JsonResponse({'error': 'No files uploaded'}, status=400)
    return JsonResponse({'error': 'Invalid request method'}, status=400)

@login_required(login_url='/superadmin/login/')
def client_update(request, pk):
    client = get_object_or_404(Client, pk=pk)
    if request.method == 'POST':
        form = ClientForm(request.POST, request.FILES, instance=client)
        if form.is_valid():
            form.save()
            messages.success(request, 'Client update successfully.')
            return JsonResponse({'client_id': client.id}, status=200) 
        else:
            return JsonResponse({'errors': form.errors}, status=400)
    else:
        form = ClientForm(instance=client)
    return render(request, 'superadmin/clients/form.html', {'form': form})

@login_required(login_url='/superadmin/login/')
def client_delete(request, client_id):
    """Handle the deletion of a single client."""
    client = get_object_or_404(Client, pk=client_id)
    if request.method == 'POST':
        client.delete()
        messages.warning(request, 'Client deleted successfully.')
        return redirect(reverse('superadmin:client_list'))
    
    return redirect(reverse('superadmin:client_list'))

@login_required(login_url='/superadmin/login/')
def bulk_client_delete(request):
    """Handle the deletion of multiple clients."""
    if request.method == 'POST':
        client_ids = request.POST.getlist('client_ids')
        if client_ids:
            # Ensure all client IDs are integers
            client_ids = [int(client_id) for client_id in client_ids]
            Client.objects.filter(pk__in=client_ids).delete()
            messages.warning(request, 'Selected clients deleted successfully.')
        else:
            messages.warning(request, 'No clients selected for deletion.')

        return redirect(reverse('superadmin:client_list'))

    return redirect(reverse('superadmin:client_list'))

def client_detail(request,client_id):
    client=get_object_or_404(Client,pk=client_id)
    client_files=client.images.all()
    projects = client.projects.all()
    
    contex={
        'client':client,
        'client_files':client_files,
        'projects':projects
    }   
    return render(request,'superadmin/clients/client_details.html',contex)

superadmin/templates/superadmin/projects/change_request_form.html
<!DOCTYPE html>
{% extends 'superadmin/base.html' %}
{% load custom_filters %}
{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header bg-secondary text-white">
                    <h3 class="card-title text-center">{{ form.instance.pk|yesno:"Update Change Request,Create Change Request" }}</h3>
                </div>
                <form method="post" action="">
                    {% csrf_token %}
                    <div class="card-body p-3">
                        {{ form.non_field_errors }}
                        <div class="table-responsive">
                            <table class="table table-borderless">
                                <tbody>
                                    <tr>
                                        <td><label for="{{ form.project.id_for_label }}">Project</label></td>
                                        <td>
                                            {{ form.project|add_class:"form-control form-control-sm" }}
                                            {{ form.project.errors }}
                                        </td>
                                    </tr>
                                    <tr>
                                        <td><label for="{{ form.task.id_for_label }}">Task</label></td>
                                        <td>
                                            {{ form.task|add_class:"form-control form-control-sm" }}
                                            {{ form.task.errors }}
                                        </td>
                                    </tr>
                                    <tr>
                                        <td><label for="{{ form.hours.id_for_label }}">Hours</label></td>
                                        <td>
                                            {{ form.hours|add_class:"form-control form-control-sm" }}
                                            {{ form.hours.errors }}
                                        </td>
                                    </tr>
                                    <tr>
                                        <td><label for="{{ form.hours.id_for_label }}">Rate($)</label></td>
                                        <td>
                                            {{ form.cost|add_class:"form-control form-control-sm" }}
                                            {{ form.cost.errors }}
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    {% if messages %}
                    <div id="message-container">
                        {% for message in messages %}
                        <div class="alert alert-warning">{{ message }}</div>
                        {% endfor %}
                    </div>
                    {% endif %}
                    <div class="card-footer text-right">
                        <button type="submit" class="btn btn-primary btn-sm">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

superadmin/templates/superadmin/projects/projects.html
<!DOCTYPE html>
{% extends "superadmin/base.html" %}

{% block content %}

{% if messages %}
<div id="message-container">
    {% for message in messages %}
    <div class="alert alert-success">{{ message }}</div>
    {% endfor %}
</div>
{% endif %}

<div class="container">
    <div class="card-body">
    <div class="header text-white py-3 px-4 my-4 rounded d-flex justify-content-between align-items-center" style="background-color:rgb(255, 255, 255)">
        <h3 class="text-dark">Projects</h3>
        <div>
            <form id="filter-form" method="get" class="form-inline justify-content-end">
                <div class="form-group mb-2 mr-2">
                    <input type="text" class="form-control" id="search-query" name="search_query" placeholder="🔍 Search by Project Title or Client Name">
                </div>
                <div class="form-group mb-2 mr-2">
                    <select class="form-control" name="client" onchange="this.form.submit()">
                        <option value="">🧑‍💼All Clients</option>
                        {% for client in clients %}
                            <option value="{{ client.id }}" {% if client_filter == client.id|stringformat:"s" %}selected{% endif %}>{{ client.name }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="form-group mb-2 mr-2">
                    <select class="form-control" name="priority" onchange="this.form.submit()">
                        <option value="">All Priorities</option>
                        {% for priority_value, priority_display in priorities %}
                            <option value="{{ priority_value }}" {% if priority_filter == priority_value %}selected{% endif %}>{{ priority_display }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="form-group mb-2 mr-2">
                    <select class="form-control" name="status" onchange="this.form.submit()">
                        <option value="">⏳All Statuses</option>
                        {% for status_value, status_display in statuses %}
                            <option value="{{ status_value }}" {% if status_filter == status_value %}selected{% endif %}>{{ status_display }}</option>
                        {% endfor %}
                    </select>
                </div>
                <a href="{% url 'superadmin:project_create' %}" class="btn btn-success ml-2"><i class="fa-solid fa-plus"></i></a>
                <button type="submit" form="bulk-delete-form" class="btn btn-danger ml-2" onclick="return confirmBulkDelete();"><i class="fa-solid fa-trash"></i></button>
            </form>
        </div>
    </div>

    <form method="post" action="{% url 'superadmin:bulk_project_delete' %}" id="bulk-delete-form">
        {% csrf_token %}
        <div class="container">
            {% for project in projects %}
            <div class="card mb-3">
                <div class="card-body kanban-task {{project.priority}} ">
                    <div class="row border-left border-primary">
                        <div class="col-md-1">
                            <input type="checkbox" name="project_ids" value="{{ project.pk }}">
                        </div>
                        <div class="col-md-4">
                            <h5 class="card-title">{{ project.project_title }}</h5>
                            <p class="card-text"><small class="text-muted">{{ project.client.name }}</small></p>
                        </div>
                          
                       
                        <!-- <div class="col-md-2">
                           
                            <p class="card-text"><small class="text-muted">{{ project.client.name }}</small></p>
                        </div> -->
                        <div class="col-md-1">
                            {% if project.priority == 'medium' %}
                                <span class="badge badge-warning">{{ project.get_priority_display }}</span>
                            {% elif project.priority == 'low' %}
                                <span class="badge badge-success">{{ project.get_priority_display }}</span>
                            {% else %}
                                <span class="badge badge-danger">{{ project.get_priority_display }}</span>
                            {% endif %}
                        </div>
                        <div class="col-md-2">
                            <p class="card-text">{{ project.start_date|date:"d/m/Y" }}-{{ project.deadline|date:"d/m/Y" }}</p>

                        </div>
                        <div class="col-md-1">
                            <p class="card-text">{{ project.project_cost }}$</p>
                        </div>
                        <div class="col-md-1">
                            {% if project.status == 'inprogress' %}
                                <span class="badge badge-warning">{{ project.get_status_display }}</span>
                            {% else %}
                                <span class="badge badge-success">{{ project.get_status_display }}</span>
                            {% endif %}
                        </div>
                        <div class="col-md-2 text-right">
                            <a href="{% url 'superadmin:project_update' project.pk %}" class="text-primary mr-2" title="Update">
                                <i class="fa-solid fa-pen-to-square"></i>
                            </a>
                            <form method="post" action="{% url 'superadmin:project_delete' project.pk %}" style="display:inline;" onsubmit="return confirmDelete();">
                                {% csrf_token %}
                                <button type="submit" class="btn p-0 text-danger mr-2" style="border: none; background: none;" title="Delete">
                                    <i class="fa-solid fa-trash"></i>
                                </button>
                            </form>
                            <a href="{% url 'superadmin:project_detail' project.pk %}" class="text-info" title="Details">
                                <i class="fas fa-info-circle fa-1x"></i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </form>
    
    
</div>
{% endblock %}

{% block extra_scripts %}
<script>
document.addEventListener('DOMContentLoaded', function() {
    document.getElementById('search-query').addEventListener('input', function(event) {
        let searchQuery = event.target.value.trim().toLowerCase();
        filterProjects(searchQuery);
    });

    function filterProjects(searchQuery) {
        let cards = document.querySelectorAll('.card'); // Targeting the card elements
        cards.forEach(card => {
            let projectTitle = card.querySelector('.card-title').textContent.toLowerCase();
            let clientName = card.querySelector('.card-text small').textContent.toLowerCase(); // Adjusted to target client name

            if (projectTitle.includes(searchQuery) || clientName.includes(searchQuery)) {
                card.style.display = '';
            } else {
                card.style.display = 'none';
            }
        });
    }

    // Confirm delete functions
    window.confirmDelete = function() {
        return confirm('Are you sure you want to delete this project?');
    }

    window.confirmBulkDelete = function() {
        return confirm('Are you sure you want to delete the selected projects?');
    }
});

</script>
{% endblock %}