coderscotchCRM/urls.py
# CoderscotchCRM/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('superadmin/', include('superadmin.urls', namespace='superadmin')),  # Avoid path conflict
    path('employee/', include('employee.urls', namespace='employee')),
    path('accounts/', include('django.contrib.auth.urls')),  # Use 'accounts/' instead of root ''
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

employee/urls.py
# employee/urls.py
from django.urls import path
from .views.authentication.loginviews import employee_login, home_view, employee_logout, employee_password_reset
from .views.taskviews import employee_tasks,task_detail
from .views.leaveviews import apply_leave,leaves
from .views.projectviews import project_list,projects
    
app_name = 'employee'
urlpatterns = [

    #login urls
    path('login/', employee_login, name='employee_login'),
    path('home/', home_view, name='home_view'),
    path('reset-password/', employee_password_reset, name='employee_password_reset'),
    path('logout/', employee_logout, name='employee_logout'),
    

    #projects urls
    path('project/', project_list, name='project_list'),
    path('projects/<int:project_id>/',projects, name='projects'),

    #tasks urls
    path('tasks/', employee_tasks, name='employee_tasks'),
    path('tasks/<int:task_id>/', task_detail, name='task_detail'),  # Add this URL pattern for task details
    
    # leaves url
    path('apply-leave/', apply_leave, name='apply_leave'),
    path('leavs/', leaves, name='leaves'),
    

   

]

superadmin/urls.py
# superadmin/urls.py
from django.urls import path

from .views import clientViews, employeeview, expenseviews, invoiceviews, leadsviews, leavesview, projectviews, taskviews
from .views import views
from django.conf import settings
from django.conf.urls.static import static



app_name = 'superadmin'

urlpatterns = [
    path('home/', views.home_view, name='home'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
   
    
    path('create-superadmin/', views.edit_superadmin, name='edit_superadmin'),
    path('profile/', views.admin_profile, name='admin_profile'),
    # Client URLs
    path('clients/', clientViews.client_list, name='client_list'),
    path('clients/create/', clientViews.client_create, name='client_create'),
    path('clients/update/<int:pk>/', clientViews.client_update, name='client_update'),
    path('clients/delete/<int:client_id>/', clientViews.client_delete, name='client_delete'),
    path('clients/bulk-delete/', clientViews.bulk_client_delete, name='bulk_client_delete'),
    path('clients/upload_images/', clientViews.upload_client_images, name='upload_client_images'),
    path('clients/details/<int:client_id>/', clientViews.client_detail, name='client_detail'),

    # Employee URLs
    path('employees/', employeeview.employee_list, name='employee_list'),
    path('employees/create/', employeeview.employee_create, name='employee_create'),
    path('employees/update/<int:pk>/', employeeview.employee_update, name='employee_update'),
    path('employees/delete/<int:pk>/', employeeview.employee_delete, name='employee_delete'),
    path('employees/upload-images/', employeeview.upload_employee_images, name='upload_employee_images'),
    path('employees/delete/<int:pk>/', employeeview.employee_delete, name='employee_delete'),
    path('employees/bulk-delete/', employeeview.bulk_employee_delete, name='bulk_employee_delete'),
    path('employees/details/<int:employee_id>/', employeeview.employee_detail, name='employee_detail'),
    path('salary-slip/<int:salary_slip_id>/pdf/', employeeview.generate_salary_slip_pdf, name='salary_slip_pdf'),
    path('salary_slip/<int:salary_slip_id>/delete/', employeeview.delete_salary_slip, name='delete_salary_slip'),
   

    
    path('employee/<int:employee_id>/create-slip/', employeeview.check_or_create_salary_slip, name='check_or_create_salary_slip'),
    path('employee/<int:employee_id>/create-salary-slip/', employeeview.create_salary_slip, name='create_salary_slip'),
    path('salary_slip/<int:salary_slip_id>/', employeeview.salary_slip_detail, name='salary_slip_detail'),
    path('salary_slip/<int:salary_slip_id>/update-slip/', employeeview.update_salary_slip, name='update_salary_slip'),
    path('project/<int:project_id>/tasks/', employeeview.project_tasks, name='project_tasks'),


    # Project URLs
    path('projects/', projectviews.project_list, name='project_list'),
    path('projects/create/', projectviews.project_create, name='project_create'),
    path('projects/<int:project_id>/edit/', projectviews.project_update, name='project_update'),
    path('projects/delete/<int:project_id>/', projectviews.project_delete, name='project_delete'),
    path('projects/bulk-delete/', projectviews.bulk_project_delete, name='bulk_project_delete'),
    path('projects/<int:project_id>/', projectviews.project_detail, name='project_detail'),
    path('projects/<int:project_id>/change-request/', projectviews.change_request_create, name='change_request_create'),
    path('projects/upload_files/', projectviews.upload_project_filess, name='upload_project_filess'),

    #Task URLS
    # path('tasks/', taskviews.task_list, name='task_list'),
   
    path('kanban/', taskviews.kanban_board, name='kanban_board'),
    path('task/create/', taskviews.create_task, name='create_task'),
    path('task/update/<int:task_id>/', taskviews.update_task, name='update_task'),
    path('tasks/<int:task_id>/delete/', taskviews.task_delete, name='task_delete'),
    path('tasks/<int:task_id>/detail/', taskviews.task_detail, name='task_detail'),
    path('tasks/add_board/', taskviews.add_board, name='add_board'),
    path('kanban/edit_board/<int:board_id>/', taskviews.edit_board, name='edit_board'),
    path('kanban/delete_board/<int:board_id>/', taskviews.delete_board, name='delete_board'),
    path('update_task_board/<int:task_id>/', taskviews.update_task_board, name='update_task_board'),
    # path('upload-task-files/', taskviews.upload_task_files, name='upload_task_filess'),
    path('fetch-employees/', taskviews.fetch_employees, name='fetch_employees'),
   
    #Leads urls
    path('leads/', leadsviews.lead_list, name='lead_list'),
    path('leads/<int:pk>/', leadsviews.lead_detail, name='lead_detail'),
    path('leads/create/', leadsviews.lead_create, name='lead_create'),
    path('leads/update/<int:pk>/', leadsviews.lead_update, name='lead_update'),
    path('leads/delete/<int:lead_id>/', leadsviews.lead_delete, name='lead_delete'),
    path('leads/bulk-delete/', leadsviews.bulk_lead_delete, name='bulk_lead_delete'),
    path('leads/upload_files/', leadsviews.upload_lead_filess, name='upload_lead_filess'),
    
    # leaves urls
    path('leave-management/', leavesview.leave_management, name='leave_list'),  # For listing all leaves
    path('leave-management/<int:leave_id>/', leavesview.leave_management, name='leave_approval'), 
    
    # invoice urls
    path('invoices/', invoiceviews.invoice_list, name='invoice_list'),
    path('invoice/<int:invoice_id>/', invoiceviews.invoice_detail, name='invoice_detail'),
    path('invoices/create/', invoiceviews.invoice_create, name='invoice_create'),
    path('invoices/add_item/', invoiceviews.add_invoice_item, name='add_invoice_item'),
    path('invoice/<int:invoice_id>/edit/', invoiceviews.invoice_edit, name='invoice_edit'),
    path('invoice/<int:invoice_id>/delete/', invoiceviews.invoice_delete, name='invoice_delete'),
    path('invoice/<int:invoice_id>/item/create/', invoiceviews.invoice_item_create, name='invoice_item_create'),
    path('invoice/<int:invoice_id>/item/<int:item_id>/delete/', invoiceviews.invoice_item_delete, name='invoice_item_delete'),
    path('invoice/<int:invoice_id>/send/', invoiceviews.send_invoice_pdf, name='send_invoice_pdf'),
    path('invoice/<int:invoice_id>/download/', invoiceviews.download_invoice_pdf, name='download_invoice_pdf'),
    
    path('expenses/', expenseviews.expense_list, name='expense_list'),
   path('expense/add/', expenseviews.add_or_update_expense, name='add_expense'),
    path('expense/update/<int:pk>/', expenseviews.add_or_update_expense, name='update_expense'),
    path('expense/delete/<int:pk>/', expenseviews.delete_expense, name='delete_expense'),
    
    
]

# Serve static files during development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

superadmin/views/clientViews.py
from django.shortcuts import render, redirect,get_object_or_404
from superadmin.models import Client,ClientImage
from django.contrib import messages
from ..forms import ClientForm,ClientImageFormSet
from django.urls import reverse
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.forms import modelformset_factory
from django.contrib.auth.decorators import login_required
from django.db.models import Q

@login_required(login_url='/superadmin/login/')
def client_list(request):
    clients = Client.objects.all().order_by('-id')
    search_query = request.GET.get('search', '').strip().lower()
    location = request.GET.get('location')
    industry = request.GET.get('industry')

    if search_query:
        clients = clients.filter(
            Q(name__icontains=search_query) |
            Q(email__icontains=search_query) |
            Q(phone__icontains=search_query)
        )
    if location:
        clients = clients.filter(location__icontains=location)
    if industry:
        clients = clients.filter(industry__icontains=industry)

    locations = Client.objects.values_list('location', flat=True).distinct()
    industries = Client.objects.values_list('industry', flat=True).distinct()

    context = {
        'clients': clients,
        'filters': request.GET,
        'locations': locations,
        'industries': industries,
    }
    return render(request, 'superadmin/clients/list.html', context)

@login_required(login_url='/superadmin/login/')
def client_create(request):
    if request.method == 'POST':
        form = ClientForm(request.POST)
        if form.is_valid():
            client = form.save()
            messages.success(request, 'Client created successfully.')
            return JsonResponse({'client_id': client.id}, status=200)
        else:
            return JsonResponse({'errors': form.errors}, status=400)
    else:
        form = ClientForm()
    
    return render(request, 'superadmin/clients/form.html', {'form': form})

@login_required(login_url='/superadmin/login/')
def upload_client_images(request):
    if request.method == 'POST':
        client_id = request.POST.get('client_id')
        client = get_object_or_404(Client, id=client_id)

        # Check if there are files in the request
        if 'file' in request.FILES:
            # Process each file
            for file in request.FILES.getlist('file'):
                ClientImage.objects.create(client=client, image=file)
            return JsonResponse({'status': 'success'}, status=200)
        else:
            return JsonResponse({'error': 'No files uploaded'}, status=400)
    return JsonResponse({'error': 'Invalid request method'}, status=400)

@login_required(login_url='/superadmin/login/')
def client_update(request, pk):
    client = get_object_or_404(Client, pk=pk)
    if request.method == 'POST':
        form = ClientForm(request.POST, request.FILES, instance=client)
        if form.is_valid():
            form.save()
            messages.success(request, 'Client update successfully.')
            return JsonResponse({'client_id': client.id}, status=200) 
        else:
            return JsonResponse({'errors': form.errors}, status=400)
    else:
        form = ClientForm(instance=client)
    return render(request, 'superadmin/clients/form.html', {'form': form})

@login_required(login_url='/superadmin/login/')
def client_delete(request, client_id):
    """Handle the deletion of a single client."""
    client = get_object_or_404(Client, pk=client_id)
    if request.method == 'POST':
        client.delete()
        messages.warning(request, 'Client deleted successfully.')
        return redirect(reverse('superadmin:client_list'))
    
    return redirect(reverse('superadmin:client_list'))

@login_required(login_url='/superadmin/login/')
def bulk_client_delete(request):
    """Handle the deletion of multiple clients."""
    if request.method == 'POST':
        client_ids = request.POST.getlist('client_ids')
        if client_ids:
            # Ensure all client IDs are integers
            client_ids = [int(client_id) for client_id in client_ids]
            Client.objects.filter(pk__in=client_ids).delete()
            messages.warning(request, 'Selected clients deleted successfully.')
        else:
            messages.warning(request, 'No clients selected for deletion.')

        return redirect(reverse('superadmin:client_list'))

    return redirect(reverse('superadmin:client_list'))

def client_detail(request,client_id):
    client=get_object_or_404(Client,pk=client_id)
    client_files=client.images.all()
    projects = client.projects.all()
    
    contex={
        'client':client,
        'client_files':client_files,
        'projects':projects
    }   
    return render(request,'superadmin/clients/client_details.html',contex)

superadmin/views/expenseviews.py
from superadmin.models import Expense
from ..forms import ExpenseForm
from django.shortcuts import render, redirect,get_object_or_404
from django.urls import reverse
from django.contrib import messages
import calendar
from datetime import datetime
from django.db.models import Q 

def expense_list(request):
    search_query = request.GET.get('search', '')


    # Start with all expenses
    expenses = Expense.objects.all().order_by('-date')

    # Filter based on search query if provided
    if search_query:
        expenses = expenses.filter(
            Q(category__icontains=search_query) |
            Q(description__icontains=search_query)
        )

 

    context = {
        'expenses': expenses,
    
    }

    return render(request, 'superadmin/expenses/expense_list.html', context)


# def add_or_update_expense(request, pk=None):
#     if pk:
#         expense = get_object_or_404(Expense, pk=pk)
#         form = ExpenseForm(request.POST or None, instance=expense)
#     else:
#         expense = None
#         form = ExpenseForm(request.POST or None)

#     if form.is_valid():
#         form.save()
#         return redirect('superadmin:expense_list')

#     return render(request, 'superadmin/expenses/add_expense.html', {'form': form, 'expense': expense})

def add_or_update_expense(request, pk=None):
    if pk:
        expense = get_object_or_404(Expense, pk=pk)
        form = ExpenseForm(request.POST or None, instance=expense)
    else:
        expense = None
        form = ExpenseForm(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect('superadmin:expense_list')

    return render(request, 'superadmin/expenses/add_expense.html', {'form': form, 'expense': expense})



# Delete view
def delete_expense(request, pk):
    expense = get_object_or_404(Expense, pk=pk)
    expense.delete()
    return redirect('superadmin:expense_list')

superadmin/views/leavesview.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from superadmin.models import Leave, LeaveAdmin

@login_required(login_url='/superadmin/login/')
def leave_management(request, leave_id=None):
    # Fetch all leaves that are not approved or cancelled
    all_leaves = Leave.objects.exclude(status__in=['approved', 'cancelled'])

    # Check if a specific leave is being managed
    leave = None
    employee_name = None
    if leave_id:
        leave = get_object_or_404(Leave, id=leave_id)
        employee = leave.employee  # Assuming 'employee' is the related user object
        employee_name = f"{employee.first_name} {employee.last_name}"  # Adjust as per your User model's fields

        if request.method == 'POST':
            action = request.POST.get('action')
            if action == 'approve':
                leave.status = 'approved'
                LeaveAdmin.objects.create(leave=leave, approved_at=timezone.now())
            elif action == 'cancel':
                leave.status = 'cancelled'
            leave.save()
            return redirect('superadmin:leave_list')  # Redirect to the leave list after action

    return render(request, 'superadmin/leaves/leave_list.html', {
        'leave': leave,
        'employee_name': employee_name,
        'all_leaves': all_leaves
    })

superadmin/templates/superadmin/invoice/invoice_detail.html
<!DOCTYPE html>
{% extends 'superadmin/base.html' %}
{% load custom_filters %}
{% block content %}
{% if messages %}
<div id="message-container">
    {% for message in messages %}
    <div class="alert alert-warning">{{ message }}</div>
    {% endfor %}
</div>
{% endif %}
<div class="container mt-5">
    <div class="card">
        <div class="card-header">
            <h5>Invoice Details</h5>
            {% if message %}
            <div class="alert alert-info">
                {{ message }}
            </div>
            {% endif %}
        </div>
        <div class="card-body">
            <p>
                {% if invoice.payment_status == 'paid' %}
                    <span class="badge badge-success">{{ invoice.payment_status }}</span>
                {% else %}
                    <span class="badge badge-danger">{{ invoice.payment_status }}</span>
                {% endif %}
            </p>
            <div class="row">
                <div class="col-md-6">
                    <p><strong>Invoice ID:</strong> {{ invoice.id }}</p>
                    <p><strong>Client:</strong> {{ invoice.client.name }}</p>
                    <p><strong>Address:</strong> {{ invoice.client.address }}</p>
                </div>
                <div class="col-md-6">
                    <p><strong>Company:</strong> {{ invoice.client.company }}</p>
                    <p><strong>Invoice Date:</strong> {{ invoice.invoice_date|date:"d/m/Y" }}</p>
                    <p><strong>Sent to Client:</strong> {% if invoice.sent_to_client %}Yes{% else %}No{% endif %}</p>
                </div>
            </div>

            <h3 class="mt-4">Invoice Items</h3>
            {% if invoice.items.all %}
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Title</th>
                        <th>Rate</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in invoice.items.all %}
                    <tr>
                        <td>{{ item.title }}</td>
                        <td>${{ item.rate }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            <div class="mt-3">
                <p><strong>Total Rate:</strong> ${{ total_rate }}</p>
                <p><strong>Tax Percentage:</strong> {{ tax_percentage }}%</p> <!-- Display tax percentage -->
                <p><strong>Tax Amount:</strong> ${{ tax_amount }}</p>
                <p><strong>Adjusted Total:</strong> ${{ adjusted_total }}</p>
            </div>
            {% else %}
            <div class="alert alert-warning" role="alert">
                No items found for this invoice.
            </div>
            {% endif %}

            <div class="mt-3">
                <form action="{% url 'superadmin:invoice_delete' invoice.id %}" method="post" class="d-inline mr-2">
                    {% csrf_token %}
                    <input type="submit" value="Delete Invoice" class="btn btn-danger" onclick="return confirmDelete()">
                </form>
                <form action="{% url 'superadmin:send_invoice_pdf' invoice.id %}" method="post" class="d-inline mr-2">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-success">Send to Client</button>
                </form>
                <form action="{% url 'superadmin:download_invoice_pdf' invoice.id %}" method="get" class="d-inline">
                    <button type="submit" class="btn btn-info">Download Invoice</button>
                </form>
            </div>
            
        </div>
        <div class="mx-4 mt-4">
            <h5>Other Invoices for {{ invoice.client }}</h5>
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Invoice ID</th>
                        <th>Invoice Date</th>
                        <th>Total Amount</th>
                        <th>Payment Status</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for client_invoice in client_invoices %}
                        <tr>
                            <td>{{ client_invoice.id }}</td>
                            <td>{{ client_invoice.invoice_date|date:"d/m/Y" }}</td>
                            <td>{{ client_invoice.total_amount }}</td>
                            <td>
                                {% if invoice.payment_status == 'paid' %}
                                <span class="badge badge-success">{{ invoice.payment_status }}</span>
                                {% else %}
                                <span class="badge badge-danger">{{ invoice.payment_status }}</span>
                                {% endif %}
                            </td>
                            <td>
                                <a href="{% url 'superadmin:invoice_detail' client_invoice.id %}" class="btn btn-primary btn-sm">View</a>
                            </td>
                        </tr>
                    {% empty %}
                        <tr>
                            <td colspan="5" class="text-center">No other invoices available for this client.</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

{% block extra_scripts %}
<script>
    function confirmDelete() {
        return confirm('Are you sure you want to delete this invoice?');
    }
</script>
{% endblock %}

superadmin/templates/superadmin/invoice/invoice_item_form.html
<!DOCTYPE html>
{% extends 'superadmin/base.html' %}
{% load custom_filters %}
{% block content %}

<body>
    <div class="container mt-5">
        <div class="card">
            <div class="card-header">
                <h2>Add Invoice Item</h2>
            </div>
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        {{ form.title.label_tag }}
                        {{ form.title|add_class:"form-control" }}
                        {{ form.title.errors }}
                    </div>
                    <div class="form-group">
                        {{ form.rate.label_tag }}
                        {{ form.rate|add_class:"form-control" }}
                        {{ form.rate.errors }}
                    </div>
                   
                    <input type="submit" value="Save" class="btn btn-primary">
                </form>
            </div>
        </div>
    </div>


</body>

{% endblock %}

superadmin/templates/superadmin/invoice/invoice_list.html
<!DOCTYPE html>
{% extends 'superadmin/base.html' %}
{% load custom_filters %}
{% block content %}

{% if messages %}
<div id="message-container">
    {% for message in messages %}
    <div class="alert alert-success">{{ message }}</div>
    {% endfor %}
</div>
{% endif %}

<div class="container mt-4">
    <div class="row">
      
            <h5 class="card-title">Invoice List</h5>
       
        <div class="col text-right">
            <form id="filter-form" method="get" class="form-inline justify-content-end">
                <div class="form-group mb-2">
                    <select class="form-control mr-2" name="payment_status" onchange="this.form.submit()">
                        <option value="">✅ All</option>
                        <option value="paid" {% if payment_status == 'paid' %}selected{% endif %}>Paid</option>
                        <option value="unpaid" {% if payment_status == 'unpaid' %}selected{% endif %}>Unpaid</option>
                    </select>
                </div>
                <div class="form-group mb-2">
                    <input type="text" class="form-control mr-2" id="search-query" name="search_query" placeholder="🔍 Search by Client" >
                </div>
                <a href="{% url 'superadmin:invoice_create' %}" class="btn btn-success mb-2">
                    <i class="fa-solid fa-plus"></i> 
                </a>
            </form>
        </div>
    </div>
    
    <div class="row">
        <div class="col">
            <table class="table table-striped table-hover">
                <thead class="thead-dark">
                    <tr>
                        <th><i class="fas fa-hashtag"></i> Invoice ID</th>
                        <th><i class="fas fa-user"></i> Client</th>
                        <th><i class="fas fa-calendar-alt"></i> Invoice Date</th>
                        <th>Payment</th>
                        <th><i class="fas fa-cogs"></i> Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for invoice in invoices %}
                    <tr>
                        <td>{{ invoice.id }}</td>
                        <td>{{ invoice.client.name }}</td>
                        <td>{{ invoice.invoice_date|date:"d/m/Y" }}</td>
                        <td >
                            {% if invoice.payment_status == 'paid' %}
                            <span class="badge badge-success">{{ invoice.payment_status }}</span>
                            {% else %}
                            <span class="badge badge-danger">{{ invoice.payment_status }}</span>
                            {% endif %}
                        </td>

                        <td>
                            <a href="{% url 'superadmin:invoice_edit' invoice.id %}" class="text-primary mr-2" title="Edit">
                                <i class="fa-solid fa-pen-to-square"></i>
                            </a>
                            <a href="{% url 'superadmin:invoice_detail' invoice.id %}" class="text-info mr-2" title="Details">
                                <i class="fas fa-info-circle"></i>
                            </a>
                        </td>
                        
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="5" class="text-center">No invoices found.</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

{% block extra_scripts %}
<script>
    document.addEventListener('DOMContentLoaded', function() {
        // Live search as you type
        document.getElementById('search-query').addEventListener('input', function(event) {
            let searchQuery = event.target.value.trim().toLowerCase();
            filterInvoices(searchQuery);
        });

        function filterInvoices(searchQuery) {
            let rows = document.querySelectorAll('tbody tr'); // Assuming your table body is structured like this
            rows.forEach(row => {
                let clientName = row.querySelector('td:nth-child(2)').textContent.toLowerCase();

                if (clientName.includes(searchQuery)) {
                    row.style.display = '';
                } else {
                    row.style.display = 'none';
                }
            });
        }

        function confirmDelete() {
            return confirm('Are you sure you want to delete this invoice?');
        }

        function confirmBulkDelete() {
            return confirm('Are you sure you want to delete the selected invoices?');
        }
    });
</script>
{% endblock %}